config/routes.rb
Rails.application.routes.draw do
  resources :clients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'El cliente se agrego correctamemnte.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Se actualizó la información correctamente' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Se eliminó el cliente correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :contact_name, :phone_number, :email, :NIT, :invoice_contact, :invoice_email, :province, :canton, :district, :contact_by, :sucursales)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :Cédula %>
    <%= form.text_field :NIT, class: "form-control", id: :client_NIT %>
  </div>

  <div class="form-group">
    <%= form.label :Compañia %>
    <%= form.text_field :name, class: "form-control", id: :client_name %>
  </div>

  <div class="form-group">
    <%= form.label :Nombre %>
    <%= form.text_field :contact_name, class: "form-control", id: :client_contact_name %>
  </div>

  <div class="form-group">
    <%= form.label :'Teléfono principal' %>
    <%= form.text_field :phone_number, class: "form-control", id: :client_phone_number %>
  </div>

  <div class="form-group">
    <%= form.label :'Teléfono secundario' %>
    <%= form.text_field :invoice_email, class: "form-control", id: :client_invoice_email %>
  </div>

  <div class="form-group">
    <%= form.label :'Correo electrónico' %>
    <%= form.text_field :email, class: "form-control", id: :client_email %>
  </div>

  <div class="form-group">
    <%= form.label :'Comentarios' %>
    <%= form.text_field :invoice_contact, class: "form-control", id: :client_invoice_contact %>
  </div>

  <div class="actions">

    <%= button_tag(type: 'submit') do %>
            Guardar
    <% end %>
  </div>

<% end %>

app/views/clients/edit.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Edición de clientes</title>
	<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse">
    <div class="img">        
      </div>
        <div class="container-fluid">
            <div class="navbar-header">               
                <img src="https://scontent.feoh3-1.fna.fbcdn.net/v/t1.0-1/13607011_1239909199382700_332108049182655267_n.png?_nc_cat=0&oh=5f359f71a0a1eaf25a947c085f584786&oe=5C11C923" height="60px" width="60px" style="position: relative; left: 85%;">
                <a class="navbar-brand" href="" style="position: relative; right: 83%; top: 18px;">CRMugui | Editar información del cliente</a>
            </div>
        </div>
    </nav> 

	<%= link_to 'Ver contacto', @client %> |
	<%= link_to 'Volver', clients_path %>
	<br />
	<br />
	<%= render 'form', client: @client %>

</body>
</html>

app/views/clients/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Clientes registradoss</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="img">        
      </div>
        <div class="container-fluid">
            <div class="navbar-header">               
                <img src="https://scontent.feoh3-1.fna.fbcdn.net/v/t1.0-1/13607011_1239909199382700_332108049182655267_n.png?_nc_cat=0&oh=5f359f71a0a1eaf25a947c085f584786&oe=5C11C923" height="60px" width="60px" style="position: relative; left: 119%;">
                <a class="navbar-brand" href="" style="position: relative; right: 115%; top: 18px;">CRMugui | Cliente registrados</a>
            </div>
        </div>
    </nav>

<p id="notice"><%= notice %></p>

<%= link_to 'Agregar', new_client_path %>

    <table class="table">
      <thead>
        <tr>
          <th scope="col">Cédula</th>
          <th scope="col">Compañia</th>
          <th scope="col">Nombre</th>
          <th scope="col">Teléfono principal</th>
          <th scope="col">Correo electrónico</th>
          <th scope="col" colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @clients.each do |client| %>
          <tr>
            <td><%= client.NIT %></td>
            <td><%= client.name %></td> 
            <td><%= client.contact_name %></td>               
            <td><%= client.phone_number %></td>        
            <td><%= client.email %></td>        
            <td><%= link_to 'Ver', client %></td>
            <td><%= link_to 'Editar', edit_client_path(client) %></td>
            <td><%= link_to 'Eliminar', client, method: :delete, data: { confirm: 'Está seguro?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

</body>
</html>

app/views/clients/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Registro de clientes</title>
	<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>
<body>	
<nav class="navbar navbar-inverse">
    <div class="img">        
      </div>
        <div class="container-fluid">
            <div class="navbar-header">               
                <img src="https://scontent.feoh3-1.fna.fbcdn.net/v/t1.0-1/13607011_1239909199382700_332108049182655267_n.png?_nc_cat=0&oh=5f359f71a0a1eaf25a947c085f584786&oe=5C11C923" height="60px" width="60px" style="position: relative; left: 135%;">
                <a class="navbar-brand" href="" style="position: relative; right: 131%; top: 18px;">CRMugui | Agregar cliente</a>
            </div>
        </div>
    </nav>

	<%= link_to 'Atras', clients_path %>
	<br />
	<br />
    <%= render 'form', client: @client %>	

</body>
</html>

app/views/clients/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Informacion de cliente</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="img">        
      </div>
        <div class="container-fluid">
            <div class="navbar-header">               
                <img src="https://scontent.feoh3-1.fna.fbcdn.net/v/t1.0-1/13607011_1239909199382700_332108049182655267_n.png?_nc_cat=0&oh=5f359f71a0a1eaf25a947c085f584786&oe=5C11C923" height="60px" width="60px" style="position: relative; left: 104%;">
                <a class="navbar-brand" href="" style="position: relative; right: 101%; top: 18px;">CRMugui | Información del cliente</a>
            </div>
        </div>
    </nav>   


<p id="notice"><%= notice %></p>

<%= link_to 'Editar', edit_client_path(@client) %> | 
<%= link_to 'Atras', clients_path %>
<br />
<br />

<p>
  <strong>Cédula:</strong>
  <%= @client.NIT %>
</p>

<p>
  <strong>Compañia:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @client.contact_name %>
</p>

<p>
  <strong>Teléfono principal:</strong>
  <%= @client.phone_number %>
</p>

<p>
  <strong>Teléfono secundario:</strong>
  <%= @client.invoice_email %>
</p>

<p>
  <strong>Correo electrónico:</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Comentarios:</strong>
  <%= @client.invoice_contact %>
</p>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MuguiCRM</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </head>

  <body>
  	<div class="container">
    	<%= yield %>
    </div>
  </body>
</html>